import { AnimalIntakeExtended } from "../models/animal-intake-extended";

export function parseAnimalIntakeExtended(data: any): AnimalIntakeExtended {
    return {
        animalId: data['Animal ID'],
        arn: data['ARN'],
        animalName: data['Animal Name'],
        species: data['Species'],
        primaryBreed: data['Primary Breed'],
        secondaryBreed: data['Secondary Breed'],
        gender: data['Gender'],
        age: data['Age'],
        altered: data['Altered'],
        danger: data['Danger'],
        dangerReason: data['Danger Reason'],
        primaryColor: data['Primary Colour'],
        secondaryColor: data['Secondary Colour'],
        thirdColor: data['Third Colour'],
        colourPattern: data['Colour Pattern'],
        secondColourPattern: data['Second Colour Pattern'],
        size: data['Size'],
        preAltered: data['Pre Altered'],
        spayNeutered: data['Spayed Neutered'],
        spayNeuteredBy: data['By'],
        recordOwner: data['Record Owner'],
        intakeDateTime: data['Intake Date/Time'],
        operationType: data['Operation Type'],
        operationSubType: data['Operation Sub Type'],
        petId: data['Pet ID'],
        petIdType: data['Pet ID Type'],
        locationFound: data['Location Found'],
        jurisdiction: data['Jurisdiction'],
        condition: data['Condition'],
        ageGroup: data['Age Group'],
        doa: data['DOA'],
        siteName: data['Site Name'],
        source: data['Source'],
        intakeReason: data['Intake Reason'],
        lengthOwned: data['Length Owned'],
        unit: data['Unit'],
        injuryType: data['Injury Type'],
        cause: data['Cause'],
        agencyName: data['Agency Name'],
        location: data['Location'],
        subLocation: data['Sub Location'],
        asilomarStatus: data['Asilomar Status'],
    }
}